In [4]:
import pandas as pd
import numpy as np

In [5]:
hr_data = pd.read_excel(r"HR_ANALYTICS_DATASET.xlsx")
hr_data.head(5)

,Employee ID,StartDate,Title,BusinessUnit,EmployeeStatus,EmployeeType,PayZone,EmployeeClassificationType,DepartmentType,Division,...,Engagement Score,Satisfaction Score,Work-Life Balance Score,Training Date,Training Program Name,Training Type,Training Outcome,Training Duration(Days),Training Cost,Age
0,3427,2019-09-20,Production Technician I,CCDR,Active,Contract,Zone C,Temporary,Production,Finance & Accounting,...,1,2,3,2023-07-15,Leadership Development,Internal,Failed,2,606.11,50
1,3428,2023-02-11,Production Technician I,EW,Active,Contract,Zone A,Part-Time,Production,Aerial,...,2,1,5,2022-09-12,Customer Service,External,Incomplete,4,673.02,58
2,3429,2018-12-10,Area Sales Manager,PL,Active,Full-Time,Zone B,Part-Time,Sales,General - Sga,...,1,2,1,2022-08-13,Leadership Development,External,Failed,2,413.28,27
3,3430,2021-06-21,Area Sales Manager,CCDR,Active,Contract,Zone A,Full-Time,Sales,Finance & Accounting,...,5,5,4,2022-12-15,Project Management,External,Completed,3,663.78,23
4,3431,2019-06-29,Area Sales Manager,TNS,Active,Contract,Zone A,Temporary,Sales,General - Con,...,2,5,3,2023-07-13,Technical Skills,External,Failed,5,399.03,50

In [6]:
hr_data_coulmns = hr_data.columns

print(hr_data_coulmns)
print(len(hr_data_coulmns))

Index(['Employee ID', 'StartDate', 'Title', 'BusinessUnit', 'EmployeeStatus',
       'EmployeeType', 'PayZone', 'EmployeeClassificationType',
       'DepartmentType', 'Division', 'DOB', 'State', 'GenderCode', 'RaceDesc',
       'MaritalDesc', 'Performance Score', 'Current Employee Rating',
       'Survey Date', 'Engagement Score', 'Satisfaction Score',
       'Work-Life Balance Score', 'Training Date', 'Training Program Name',
       'Training Type', 'Training Outcome', 'Training Duration(Days)',
       'Training Cost', 'Age'],
      dtype='object')
28

In [7]:
hr_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2845 entries, 0 to 2844
Data columns (total 28 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee ID                 2845 non-null   int64
 1   StartDate                   2845 non-null   datetime64[ns]
 2   Title                       2845 non-null   object
 3   BusinessUnit                2845 non-null   object
 4   EmployeeStatus              2845 non-null   object
 5   EmployeeType                2845 non-null   object
 6   PayZone                     2845 non-null   object
 7   EmployeeClassificationType  2845 non-null   object
 8   DepartmentType              2845 non-null   object
 9   Division                    2845 non-null   object
 10  DOB                         2845 non-null   datetime64[ns]
 11  State                       2845 non-null   object
 12  GenderCode                  2845 non-null   object
 13  RaceDesc                    2845 non-null   object
 14  MaritalDesc                 2845 non-null   object
 15  Performance Score           2845 non-null   object
 16  Current Employee Rating     2845 non-null   int64
 17  Survey Date                 2845 non-null   datetime64[ns]
 18  Engagement Score            2845 non-null   int64
 19  Satisfaction Score          2845 non-null   int64
 20  Work-Life Balance Score     2845 non-null   int64
 21  Training Date               2845 non-null   datetime64[ns]
 22  Training Program Name       2845 non-null   object
 23  Training Type               2845 non-null   object
 24  Training Outcome            2845 non-null   object
 25  Training Duration(Days)     2845 non-null   int64
 26  Training Cost               2845 non-null   float64
 27  Age                         2845 non-null   int64
dtypes: datetime64[ns](4), float64(1), int64(7), object(16)
memory usage: 622.5+ KB

In [9]:
hr_data.rename(columns={
    "Employee ID":"employee_id",
    "StartDate":"start_date",
    "Title":"title",
    "BusinessUnit":"business_nit",
    "EmployeeStatus":"employee_status",
    "EmployeeType":"employee_type",
    "PayZone":"pay_zone",
    "EmployeeClassificationType":"employee_classification_type",
    "DepartmentType":"department_type",
    "Division":"division",
    "DOB":"d_o_b",
    "State":"state",
    "GenderCode":"gender_code",
    "RaceDesc":"race_desc",
    "MaritalDesc":"marital_desc",
    "Performance Score":"performance_score",
    "Current Employee Rating":"current_employee_rating",
    "Survey Date":"survey_date",
    "Engagement Score":"engagement_score",
    "Satisfaction Score":"satisfaction_core",
    "Work-Life Balance Score":"work_life_balance_score",
    "Training Date":"training_date",
    "Training Program Name":"training_program_name",
    "Training Type":"training_type",
    "Training Outcome":"training_outcome",
    "Training Duration(Days)":"training_duration_days",
    "Training Cost":"training_cost",
    "Age":"age",
})
hr_data.head(5)

,Employee ID,StartDate,Title,BusinessUnit,EmployeeStatus,EmployeeType,PayZone,EmployeeClassificationType,DepartmentType,Division,...,Engagement Score,Satisfaction Score,Work-Life Balance Score,Training Date,Training Program Name,Training Type,Training Outcome,Training Duration(Days),Training Cost,Age
0,3427,2019-09-20,Production Technician I,CCDR,Active,Contract,Zone C,Temporary,Production,Finance & Accounting,...,1,2,3,2023-07-15,Leadership Development,Internal,Failed,2,606.11,50
1,3428,2023-02-11,Production Technician I,EW,Active,Contract,Zone A,Part-Time,Production,Aerial,...,2,1,5,2022-09-12,Customer Service,External,Incomplete,4,673.02,58
2,3429,2018-12-10,Area Sales Manager,PL,Active,Full-Time,Zone B,Part-Time,Sales,General - Sga,...,1,2,1,2022-08-13,Leadership Development,External,Failed,2,413.28,27
3,3430,2021-06-21,Area Sales Manager,CCDR,Active,Contract,Zone A,Full-Time,Sales,Finance & Accounting,...,5,5,4,2022-12-15,Project Management,External,Completed,3,663.78,23
4,3431,2019-06-29,Area Sales Manager,TNS,Active,Contract,Zone A,Temporary,Sales,General - Con,...,2,5,3,2023-07-13,Technical Skills,External,Failed,5,399.03,50